// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_PLATFORM_REPO.Models;

public partial class Order
{
    public long OrderId { get; set; }

    public long? ShopId { get; set; }

    public long? ProductId { get; set; }

    public long? UserId { get; set; }

    public decimal? TotalPrice { get; set; }

    public string PaymentMethod { get; set; }

    public short? Status { get; set; }

    public decimal? Discount { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? ExpiredAt { get; set; }

    public string Note { get; set; }

    public virtual Product Product { get; set; }

    public virtual Shop Shop { get; set; }

    public virtual User User { get; set; }
}