// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_PLATFORM_REPO.Models;

public partial class Product
{
    public long ProductId { get; set; }

    public string ProductName { get; set; }

    public string Description { get; set; }

    public decimal? Price { get; set; }

    public int? RequestLimit { get; set; }

    public int? AccountLimit { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public decimal? Discount { get; set; }

    public short? Status { get; set; }

    public string QrcodeUrl { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<PromotionProduct> PromotionProducts { get; set; } = new List<PromotionProduct>();

    public virtual ICollection<ReportDetail> ReportDetails { get; set; } = new List<ReportDetail>();
}