// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_PLATFORM_REPO.Models;

public partial class Report
{
    public long ReportId { get; set; }

    public string Type { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? OrderCounter { get; set; }

    public decimal? Revenue { get; set; }

    public virtual ICollection<ReportDetail> ReportDetails { get; set; } = new List<ReportDetail>();
}