// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_PLATFORM_REPO.Models;

public partial class Shop
{
    public long ShopId { get; set; }

    public string ShopName { get; set; }

    public string Address { get; set; }

    public short? Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Fullname { get; set; }

    public string Phonenumber { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}