// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASA_PLATFORM_REPO.Models;

public partial class User
{
    public long UserId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public short? Status { get; set; }

    public short? Role { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Avatar { get; set; }

    public virtual ICollection<LogActivity> LogActivities { get; set; } = new List<LogActivity>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}